HourlyFE/Controllers/BlogController.cs
using System.Web.Mvc;


namespace HourlyFE.Controllers
{
    
    
    public class BlogController : Controller
    {
        
        public ActionResult Home1()
        {
            return View();
        }
        
        public ActionResult Post()
        {
            return View();
        }
    }
}

HourlyFE/Controllers/OtherController.cs
using System.Web.Mvc;


namespace HourlyFE.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

HourlyFE/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace HourlyFE.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult ThreeColumn()
        {
            return View();
        }
    }
}

HourlyFE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <link href="@Url.Content("/css/CustomStyles.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css">

    <!--Data Table-->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>


    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("HourlyFE", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="Employees">
                        @Html.ActionLink("Employee", "Index", "Employee")
                    </li>
                    <li id="Timesheets">
                        @Html.ActionLink("Timesheet", "Index", "Timesheet")
                    </li>
                    <li id="Employees">
                        @Html.ActionLink("Company", "Index", "Company")
                    </li>
                    @*<li id="about">
                           @Html.ActionLink("About", "Index", "About")
                        </li>
                        <li id="services">
                            @Html.ActionLink("Services", "Index", "Services")
                        </li>*@
                    <li id="contact">
                        @Html.ActionLink("Contact", "Index", "Contact")
                    </li>
                    <li id="portfolio" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">


                            <li id="3columnportfolio">
                                @Html.ActionLink("3 Column Portfolio", "ThreeColumn", "Portfolio")
                            </li>


                        </ul>
                    </li>
                    <li id="blog" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="bloghome1">
                                @Html.ActionLink("Blog Home 1", "Home1", "Blog")
                            </li>

                            <li id="blogpost">
                                @Html.ActionLink("Blog Post", "Post", "Blog")
                            </li>
                        </ul>
                    </li>
                    <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            <li id="faq">
                                @Html.ActionLink("FAQ", "Faq", "Other")
                            </li>
                            <li id="404">
                                @Html.ActionLink("404", "FourOhFour", "Other")
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container-fluid">
        <div class="row full-width-row-margin">
            <div class="col-md-2 col-sm-4 sidebar">
                @{
                    var module = "Employee";
                    //var role = getMenuBasedOnModule();
                    if (ViewBag.Title == "Employee-Hourly") //if module == getusermodule()
                    {
                        <ul class="nav nav-stacked nav-pills">
                            <li>
                                <a href="#">Employee</a>
                            </li>
                            <li>
                                <a href="#">Employee Menu2</a>
                            </li>
                        </ul>
                    }
                    else if (ViewBag.Title == "Company-Hourly") //if module == getusermodule()
                    {
                        <ul class="nav nav-stacked nav-pills">
                            <li>
                                @Html.ActionLink("Company", "Index", "Company")
                            </li>
                            <li>
                                <a href="#">Company Menu</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav nav-stacked nav-pills">
                            <li>
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li>
                                <a href="#">About</a>
                            </li>
                            <li>
                                <a href="#">Services</a>
                            </li>
                            <li>
                                <a href="#">Contact</a>
                            </li>
                            <li class="disabled">
                                <a href="#">Portfolio</a>
                            </li>
                            <li>
                                <a href="#">1 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="#">2 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="#">3 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="#">4 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="#">Single Portfolio Item</a>
                            </li>
                            <li class="disabled">
                                <a href="#">Blog</a>
                            </li>
                            <li>
                                <a href="#">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="#">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="#">Blog Post</a>
                            </li>
                            <li class="disabled">
                                <a href="#">Blog</a>
                            </li>
                            <li>
                                <a href="#">Full Width Page</a>
                            </li>
                            <li class="active">
                                <a href="#">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="#">FAQ</a>
                            </li>
                            <li>
                                <a href="#">404</a>
                            </li>
                            <li>
                                <a href="#">Pricing Table</a>
                            </li>
                        </ul>
                    }
                }
                
            </div>
            <div class="col-md-10 col-sm-8">
                @RenderBody()
            </div>
        </div>
        <!-- /.row -->
    </div>
    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

   
</body>
</html>